In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv("Training_set_boston.csv")
df.shape

(404, 14)

In [4]:
df.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,15.02340,0.0,18.10,0.0,0.6140,5.304,97.3,2.1007,24.0,666.0,20.2,349.48,24.91,12.0
1,0.62739,0.0,8.14,0.0,0.5380,5.834,56.5,4.4986,4.0,307.0,21.0,395.62,8.47,19.9
2,0.03466,35.0,6.06,0.0,0.4379,6.031,23.3,6.6407,1.0,304.0,16.9,362.25,7.83,19.4
3,7.05042,0.0,18.10,0.0,0.6140,6.103,85.1,2.0218,24.0,666.0,20.2,2.52,23.29,13.4
4,0.72580,0.0,8.14,0.0,0.5380,5.727,69.5,3.7965,4.0,307.0,21.0,390.95,11.28,18.2

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 404 entries, 0 to 403
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   CRIM     404 non-null    float64
 1   ZN       404 non-null    float64
 2   INDUS    404 non-null    float64
 3   CHAS     404 non-null    float64
 4   NOX      404 non-null    float64
 5   RM       404 non-null    float64
 6   AGE      404 non-null    float64
 7   DIS      404 non-null    float64
 8   RAD      404 non-null    float64
 9   TAX      404 non-null    float64
 10  PTRATIO  404 non-null    float64
 11  B        404 non-null    float64
 12  LSTAT    404 non-null    float64
 13  MEDV     404 non-null    float64
dtypes: float64(14)
memory usage: 44.3 KB

In [6]:
df.describe()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
count,404.000000,404.000000,404.000000,404.000000,404.000000,404.000000,404.000000,404.000000,404.000000,404.000000,404.000000,404.000000,404.000000,404.000000
mean,3.609125,11.569307,10.985050,0.071782,0.556484,6.315891,68.556436,3.808195,9.356436,404.032178,18.318317,356.278342,12.457351,22.796535
std,8.875058,23.152481,6.894618,0.258447,0.117704,0.709452,27.994922,2.131226,8.589721,166.172655,2.228701,91.566533,7.110381,9.332147
min,0.009060,0.000000,0.740000,0.000000,0.385000,3.863000,2.900000,1.129600,1.000000,187.000000,12.600000,0.320000,1.730000,5.000000
25%,0.081437,0.000000,5.130000,0.000000,0.452000,5.890500,45.550000,2.087875,4.000000,279.000000,16.800000,375.472500,6.772500,16.950000
50%,0.261390,0.000000,8.560000,0.000000,0.538000,6.210000,77.700000,3.175750,5.000000,330.000000,18.700000,391.305000,10.925000,21.600000
75%,3.202962,20.000000,18.100000,0.000000,0.631000,6.636750,93.650000,5.400800,12.000000,666.000000,20.200000,395.755000,16.372500,26.400000
max,88.976200,100.000000,27.740000,1.000000,0.871000,8.780000,100.000000,12.126500,24.000000,711.000000,22.000000,396.900000,37.970000,50.000000

In [7]:
df.nunique()

CRIM       403
ZN          25
INDUS       72
CHAS         2
NOX         80
RM         366
AGE        304
DIS        336
RAD          9
TAX         64
PTRATIO     45
B          290
LSTAT      370
MEDV       207
dtype: int64

In [8]:
# CHAS and RAD seem to be categorical features so let us explore them

In [9]:
df['CHAS'].value_counts()

0.0    375
1.0     29
Name: CHAS, dtype: int64

In [10]:
df['RAD'].value_counts()

24.0    101
5.0      94
4.0      80
3.0      32
6.0      23
2.0      21
8.0      21
1.0      17
7.0      15
Name: RAD, dtype: int64

In [11]:
#RAD is an Ordinal Categorical Feature si we are not going to do any changes to it
#However,we have to convert CHAS to actegorical feature and create dummy data from it

In [12]:
df = pd.get_dummies(df,columns = ['CHAS'],drop_first = True)
df.head()

,CRIM,ZN,INDUS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV,CHAS_1.0
0,15.02340,0.0,18.10,0.6140,5.304,97.3,2.1007,24.0,666.0,20.2,349.48,24.91,12.0,0
1,0.62739,0.0,8.14,0.5380,5.834,56.5,4.4986,4.0,307.0,21.0,395.62,8.47,19.9,0
2,0.03466,35.0,6.06,0.4379,6.031,23.3,6.6407,1.0,304.0,16.9,362.25,7.83,19.4,0
3,7.05042,0.0,18.10,0.6140,6.103,85.1,2.0218,24.0,666.0,20.2,2.52,23.29,13.4,0
4,0.72580,0.0,8.14,0.5380,5.727,69.5,3.7965,4.0,307.0,21.0,390.95,11.28,18.2,0

In [13]:
#Let us also round off age

df['AGE'] = np.round(df['AGE'])
df.head()

,CRIM,ZN,INDUS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV,CHAS_1.0
0,15.02340,0.0,18.10,0.6140,5.304,97.0,2.1007,24.0,666.0,20.2,349.48,24.91,12.0,0
1,0.62739,0.0,8.14,0.5380,5.834,56.0,4.4986,4.0,307.0,21.0,395.62,8.47,19.9,0
2,0.03466,35.0,6.06,0.4379,6.031,23.0,6.6407,1.0,304.0,16.9,362.25,7.83,19.4,0
3,7.05042,0.0,18.10,0.6140,6.103,85.0,2.0218,24.0,666.0,20.2,2.52,23.29,13.4,0
4,0.72580,0.0,8.14,0.5380,5.727,70.0,3.7965,4.0,307.0,21.0,390.95,11.28,18.2,0

In [14]:
#Seperate Independent and dependent features
X = df.drop('MEDV',axis = 1)
y = df['MEDV']

In [15]:
X.shape,y.shape

((404, 13), (404,))

In [16]:
#Split train and test
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state = 42)

In [17]:
#Define Your Model

from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense
from numpy.random import seed

In [18]:
model = Sequential()
model.add(Dense(10,activation = 'relu',input_shape = (X.shape[1],)))
model.add(Dense(8,activation = 'relu'))
model.add(Dense(1))

In [19]:
#Compile the model
from tensorflow.keras.optimizers import RMSprop

optimizer = RMSprop(0.01)
model.compile(loss = 'mean_squared_error',optimizer = optimizer)

In [20]:
import random
random.seed(42)

In [21]:
#Fit the model
model.fit(X_train,y_train,epochs = 10,batch_size = 30,verbose = 1)

Epoch 1/10
11/11 [==============================] - 1s 2ms/step - loss: 25875.0039
Epoch 2/10
11/11 [==============================] - 0s 2ms/step - loss: 700.4223
Epoch 3/10
11/11 [==============================] - 0s 2ms/step - loss: 208.1327
Epoch 4/10
11/11 [==============================] - 0s 2ms/step - loss: 178.3637
Epoch 5/10
11/11 [==============================] - 0s 2ms/step - loss: 166.0662
Epoch 6/10
11/11 [==============================] - 0s 2ms/step - loss: 233.5717
Epoch 7/10
11/11 [==============================] - 0s 2ms/step - loss: 183.7256
Epoch 8/10
11/11 [==============================] - 0s 2ms/step - loss: 171.7779
Epoch 9/10
11/11 [==============================] - 0s 2ms/step - loss: 195.6135
Epoch 10/10
11/11 [==============================] - 0s 2ms/step - loss: 82.9639

In [22]:
model.evaluate(X_test,y_test)

3/3 [==============================] - 0s 5ms/step - loss: 91.7236

91.72364807128906

In [23]:
#HperParameter tuning
from keras.wrappers.scikit_learn import KerasRegressor
from sklearn.model_selection import GridSearchCV

def create_model():
  model = Sequential()
  model.add(Dense(10,activation = 'relu',input_shape = (X_train.shape[1],)))
  model.add(Dense(8,activation = 'relu'))
  model.add(Dense(1))
  model.compile(loss = 'mse',metrics = 'mse',optimizer = RMSprop(0.01))
  model.fit(X_train,y_train)
  return model

model = KerasRegressor(build_fn=create_model,verbose = 1)
param_grid= {'batch_size':[10,20,30,40,50,60,80],
             'epochs':[5,10,50,100]}

model = KerasRegressor(build_fn=create_model,verbose = 1)
grid = GridSearchCV(estimator = model,param_grid = param_grid,cv = 5,n_jobs = -1)

grid.fit(X_train,y_train,verbose = 1)

print(grid.best_params_)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:14: DeprecationWarning: KerasRegressor is deprecated, use Sci-Keras (https://github.com/adriangb/scikeras) instead. See https://www.adriangb.com/scikeras/stable/migration.html for help migrating.

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:18: DeprecationWarning: KerasRegressor is deprecated, use Sci-Keras (https://github.com/adriangb/scikeras) instead. See https://www.adriangb.com/scikeras/stable/migration.html for help migrating.

11/11 [==============================] - 1s 2ms/step - loss: 148.0926 - mse: 148.0926
Epoch 1/100
11/11 [==============================] - 0s 2ms/step - loss: 82.5833 - mse: 82.5833
Epoch 2/100
11/11 [==============================] - 0s 2ms/step - loss: 86.5431 - mse: 86.5431
Epoch 3/100
11/11 [==============================] - 0s 2ms/step - loss: 82.7975 - mse: 82.7975
Epoch 4/100
11/11 [==============================] - 0s 2ms/step - loss: 82.2635 - mse: 82.2635
Epoch 5/100
11/11 [==============================] - 0s 2ms/step - loss: 68.7089 - mse: 68.7089
Epoch 6/100
11/11 [==============================] - 0s 2ms/step - loss: 73.1782 - mse: 73.1782
Epoch 7/100
11/11 [==============================] - 0s 2ms/step - loss: 69.2150 - mse: 69.2150
Epoch 8/100
11/11 [==============================] - 0s 2ms/step - loss: 70.5688 - mse: 70.5688
Epoch 9/100
11/11 [==============================] - 0s 2ms/step - loss: 67.8172 - mse: 67.8172
Epoch 10/100
11/11 [==============================] - 0s 2ms/step - loss: 60.5177 - mse: 60.5177
Epoch 11/100
11/11 [==============================] - 0s 3ms/step - loss: 63.6767 - mse: 63.6767
Epoch 12/100
11/11 [==============================] - 0s 3ms/step - loss: 62.0284 - mse: 62.0284
Epoch 13/100
11/11 [==============================] - 0s 3ms/step - loss: 63.4889 - mse: 63.4889
Epoch 14/100
11/11 [==============================] - 0s 3ms/step - loss: 56.5462 - mse: 56.5462
Epoch 15/100
11/11 [==============================] - 0s 2ms/step - loss: 54.9623 - mse: 54.9623
Epoch 16/100
11/11 [==============================] - 0s 3ms/step - loss: 61.4365 - mse: 61.4365
Epoch 17/100
11/11 [==============================] - 0s 2ms/step - loss: 55.8226 - mse: 55.8226
Epoch 18/100
11/11 [==============================] - 0s 2ms/step - loss: 56.6489 - mse: 56.6489
Epoch 19/100
11/11 [==============================] - 0s 2ms/step - loss: 51.6536 - mse: 51.6536
Epoch 20/100
11/11 [==============================] - 0s 2ms/step - loss: 56.9880 - mse: 56.9880
Epoch 21/100
11/11 [==============================] - 0s 3ms/step - loss: 55.9262 - mse: 55.9262
Epoch 22/100
11/11 [==============================] - 0s 3ms/step - loss: 46.8788 - mse: 46.8788
Epoch 23/100
11/11 [==============================] - 0s 2ms/step - loss: 51.7371 - mse: 51.7371
Epoch 24/100
11/11 [==============================] - 0s 3ms/step - loss: 59.3287 - mse: 59.3287
Epoch 25/100
11/11 [==============================] - 0s 2ms/step - loss: 42.7443 - mse: 42.7443
Epoch 26/100
11/11 [==============================] - 0s 2ms/step - loss: 55.9832 - mse: 55.9832
Epoch 27/100
11/11 [==============================] - 0s 3ms/step - loss: 48.1053 - mse: 48.1053
Epoch 28/100
11/11 [==============================] - 0s 2ms/step - loss: 44.7783 - mse: 44.7783
Epoch 29/100
11/11 [==============================] - 0s 2ms/step - loss: 51.9284 - mse: 51.9284
Epoch 30/100
11/11 [==============================] - 0s 2ms/step - loss: 45.9584 - mse: 45.9584
Epoch 31/100
11/11 [==============================] - 0s 3ms/step - loss: 49.5975 - mse: 49.5975
Epoch 32/100
11/11 [==============================] - 0s 3ms/step - loss: 42.9372 - mse: 42.9372
Epoch 33/100
11/11 [==============================] - 0s 2ms/step - loss: 56.2511 - mse: 56.2511
Epoch 34/100
11/11 [==============================] - 0s 3ms/step - loss: 41.2230 - mse: 41.2230
Epoch 35/100
11/11 [==============================] - 0s 3ms/step - loss: 49.6753 - mse: 49.6753
Epoch 36/100
11/11 [==============================] - 0s 2ms/step - loss: 39.6734 - mse: 39.6734
Epoch 37/100
11/11 [==============================] - 0s 2ms/step - loss: 42.1899 - mse: 42.1899
Epoch 38/100
11/11 [==============================] - 0s 3ms/step - loss: 47.5613 - mse: 47.5613
Epoch 39/100
11/11 [==============================] - 0s 3ms/step - loss: 49.3807 - mse: 49.3807
Epoch 40/100
11/11 [==============================] - 0s 3ms/step - loss: 44.0651 - mse: 44.0651
Epoch 41/100
11/11 [==============================] - 0s 2ms/step - loss: 35.2336 - mse: 35.2336
Epoch 42/100
11/11 [==============================] - 0s 2ms/step - loss: 48.7381 - mse: 48.7381
Epoch 43/100
11/11 [==============================] - 0s 2ms/step - loss: 41.5795 - mse: 41.5795
Epoch 44/100
11/11 [==============================] - 0s 2ms/step - loss: 43.8683 - mse: 43.8683
Epoch 45/100
11/11 [==============================] - 0s 3ms/step - loss: 46.3565 - mse: 46.3565
Epoch 46/100
11/11 [==============================] - 0s 3ms/step - loss: 45.1785 - mse: 45.1785
Epoch 47/100
11/11 [==============================] - 0s 3ms/step - loss: 47.6294 - mse: 47.6294
Epoch 48/100
11/11 [==============================] - 0s 3ms/step - loss: 37.5267 - mse: 37.5267
Epoch 49/100
11/11 [==============================] - 0s 3ms/step - loss: 38.0470 - mse: 38.0470
Epoch 50/100
11/11 [==============================] - 0s 3ms/step - loss: 46.1701 - mse: 46.1701
Epoch 51/100
11/11 [==============================] - 0s 2ms/step - loss: 29.2549 - mse: 29.2549
Epoch 52/100
11/11 [==============================] - 0s 2ms/step - loss: 35.8142 - mse: 35.8142
Epoch 53/100
11/11 [==============================] - 0s 2ms/step - loss: 41.2333 - mse: 41.2333
Epoch 54/100
11/11 [==============================] - 0s 2ms/step - loss: 38.1793 - mse: 38.1793
Epoch 55/100
11/11 [==============================] - 0s 2ms/step - loss: 40.6753 - mse: 40.6753
Epoch 56/100
11/11 [==============================] - 0s 2ms/step - loss: 36.1999 - mse: 36.1999
Epoch 57/100
11/11 [==============================] - 0s 3ms/step - loss: 35.1466 - mse: 35.1466
Epoch 58/100
11/11 [==============================] - 0s 3ms/step - loss: 44.5559 - mse: 44.5559
Epoch 59/100
11/11 [==============================] - 0s 2ms/step - loss: 36.8357 - mse: 36.8357
Epoch 60/100
11/11 [==============================] - 0s 3ms/step - loss: 37.9258 - mse: 37.9258
Epoch 61/100
11/11 [==============================] - 0s 2ms/step - loss: 34.4361 - mse: 34.4361
Epoch 62/100
11/11 [==============================] - 0s 2ms/step - loss: 36.7639 - mse: 36.7639
Epoch 63/100
11/11 [==============================] - 0s 2ms/step - loss: 37.3570 - mse: 37.3570
Epoch 64/100
11/11 [==============================] - 0s 2ms/step - loss: 28.7148 - mse: 28.7148
Epoch 65/100
11/11 [==============================] - 0s 2ms/step - loss: 36.2395 - mse: 36.2395
Epoch 66/100
11/11 [==============================] - 0s 3ms/step - loss: 32.2901 - mse: 32.2901
Epoch 67/100
11/11 [==============================] - 0s 2ms/step - loss: 34.8593 - mse: 34.8593
Epoch 68/100
11/11 [==============================] - 0s 3ms/step - loss: 39.5765 - mse: 39.5765
Epoch 69/100
11/11 [==============================] - 0s 2ms/step - loss: 26.6203 - mse: 26.6203
Epoch 70/100
11/11 [==============================] - 0s 2ms/step - loss: 41.5820 - mse: 41.5820
Epoch 71/100
11/11 [==============================] - 0s 2ms/step - loss: 40.6468 - mse: 40.6468
Epoch 72/100
11/11 [==============================] - 0s 2ms/step - loss: 27.0170 - mse: 27.0170
Epoch 73/100
11/11 [==============================] - 0s 2ms/step - loss: 32.2461 - mse: 32.2461
Epoch 74/100
11/11 [==============================] - 0s 2ms/step - loss: 32.5113 - mse: 32.5113
Epoch 75/100
11/11 [==============================] - 0s 2ms/step - loss: 35.3079 - mse: 35.3079
Epoch 76/100
11/11 [==============================] - 0s 3ms/step - loss: 28.5814 - mse: 28.5814
Epoch 77/100
11/11 [==============================] - 0s 2ms/step - loss: 34.9291 - mse: 34.9291
Epoch 78/100
11/11 [==============================] - 0s 2ms/step - loss: 32.5627 - mse: 32.5627
Epoch 79/100
11/11 [==============================] - 0s 2ms/step - loss: 33.9333 - mse: 33.9333
Epoch 80/100
11/11 [==============================] - 0s 2ms/step - loss: 33.6140 - mse: 33.6140
Epoch 81/100
11/11 [==============================] - 0s 2ms/step - loss: 28.6608 - mse: 28.6608
Epoch 82/100
11/11 [==============================] - 0s 2ms/step - loss: 35.6538 - mse: 35.6538
Epoch 83/100
11/11 [==============================] - 0s 2ms/step - loss: 36.0505 - mse: 36.0505
Epoch 84/100
11/11 [==============================] - 0s 2ms/step - loss: 26.1119 - mse: 26.1119
Epoch 85/100
11/11 [==============================] - 0s 2ms/step - loss: 34.3300 - mse: 34.3300
Epoch 86/100
11/11 [==============================] - 0s 2ms/step - loss: 28.7687 - mse: 28.7687
Epoch 87/100
11/11 [==============================] - 0s 2ms/step - loss: 27.1832 - mse: 27.1832
Epoch 88/100
11/11 [==============================] - 0s 2ms/step - loss: 34.8392 - mse: 34.8392
Epoch 89/100
11/11 [==============================] - 0s 2ms/step - loss: 32.4088 - mse: 32.4088
Epoch 90/100
11/11 [==============================] - 0s 2ms/step - loss: 35.9503 - mse: 35.9503
Epoch 91/100
11/11 [==============================] - 0s 2ms/step - loss: 29.4856 - mse: 29.4856
Epoch 92/100
11/11 [==============================] - 0s 2ms/step - loss: 24.8248 - mse: 24.8248
Epoch 93/100
11/11 [==============================] - 0s 2ms/step - loss: 36.8988 - mse: 36.8988
Epoch 94/100
11/11 [==============================] - 0s 2ms/step - loss: 35.1763 - mse: 35.1763
Epoch 95/100
11/11 [==============================] - 0s 2ms/step - loss: 29.4272 - mse: 29.4272
Epoch 96/100
11/11 [==============================] - 0s 2ms/step - loss: 35.1397 - mse: 35.1397
Epoch 97/100
11/11 [==============================] - 0s 2ms/step - loss: 24.5349 - mse: 24.5349
Epoch 98/100
11/11 [==============================] - 0s 2ms/step - loss: 38.7458 - mse: 38.7458
Epoch 99/100
11/11 [==============================] - 0s 3ms/step - loss: 34.7471 - mse: 34.7471
Epoch 100/100
11/11 [==============================] - 0s 3ms/step - loss: 21.8616 - mse: 21.8616
{'batch_size': 30, 'epochs': 100}

In [24]:
model = Sequential()
model.add(Dense(10,activation = 'relu',input_shape = (X.shape[1],)))
model.add(Dense(8,activation = 'relu'))
model.add(Dense(1))

In [25]:
from tensorflow.keras.optimizers import RMSprop

optimizer = RMSprop(0.01)
model.compile(loss = 'mean_squared_error',optimizer = optimizer)

In [26]:
import random
random.seed(42)

In [27]:
model.fit(X_train,y_train,epochs = 100,batch_size = 10,verbose = 1)

Epoch 1/100
33/33 [==============================] - 1s 2ms/step - loss: 149.6268
Epoch 2/100
33/33 [==============================] - 0s 2ms/step - loss: 88.3973
Epoch 3/100
33/33 [==============================] - 0s 2ms/step - loss: 80.2741
Epoch 4/100
33/33 [==============================] - 0s 2ms/step - loss: 78.4546
Epoch 5/100
33/33 [==============================] - 0s 2ms/step - loss: 79.1410
Epoch 6/100
33/33 [==============================] - 0s 2ms/step - loss: 75.0112
Epoch 7/100
33/33 [==============================] - 0s 2ms/step - loss: 71.3540
Epoch 8/100
33/33 [==============================] - 0s 2ms/step - loss: 67.4334
Epoch 9/100
33/33 [==============================] - 0s 2ms/step - loss: 68.4629
Epoch 10/100
33/33 [==============================] - 0s 1ms/step - loss: 64.1602
Epoch 11/100
33/33 [==============================] - 0s 2ms/step - loss: 61.5772
Epoch 12/100
33/33 [==============================] - 0s 2ms/step - loss: 59.8078
Epoch 13/100
33/33 [==============================] - 0s 2ms/step - loss: 56.1600
Epoch 14/100
33/33 [==============================] - 0s 1ms/step - loss: 53.9620
Epoch 15/100
33/33 [==============================] - 0s 1ms/step - loss: 58.3789
Epoch 16/100
33/33 [==============================] - 0s 1ms/step - loss: 51.8341
Epoch 17/100
33/33 [==============================] - 0s 2ms/step - loss: 50.9733
Epoch 18/100
33/33 [==============================] - 0s 2ms/step - loss: 52.9166
Epoch 19/100
33/33 [==============================] - 0s 2ms/step - loss: 50.1892
Epoch 20/100
33/33 [==============================] - 0s 2ms/step - loss: 48.0774
Epoch 21/100
33/33 [==============================] - 0s 2ms/step - loss: 45.8275
Epoch 22/100
33/33 [==============================] - 0s 2ms/step - loss: 48.5534
Epoch 23/100
33/33 [==============================] - 0s 2ms/step - loss: 48.6867
Epoch 24/100
33/33 [==============================] - 0s 2ms/step - loss: 44.9496
Epoch 25/100
33/33 [==============================] - 0s 2ms/step - loss: 43.5722
Epoch 26/100
33/33 [==============================] - 0s 2ms/step - loss: 43.3353
Epoch 27/100
33/33 [==============================] - 0s 2ms/step - loss: 46.1376
Epoch 28/100
33/33 [==============================] - 0s 1ms/step - loss: 41.5473
Epoch 29/100
33/33 [==============================] - 0s 2ms/step - loss: 44.8962
Epoch 30/100
33/33 [==============================] - 0s 1ms/step - loss: 40.9882
Epoch 31/100
33/33 [==============================] - 0s 2ms/step - loss: 41.3455
Epoch 32/100
33/33 [==============================] - 0s 2ms/step - loss: 43.0289
Epoch 33/100
33/33 [==============================] - 0s 2ms/step - loss: 41.6062
Epoch 34/100
33/33 [==============================] - 0s 2ms/step - loss: 44.3517
Epoch 35/100
33/33 [==============================] - 0s 2ms/step - loss: 39.4249
Epoch 36/100
33/33 [==============================] - 0s 2ms/step - loss: 45.0750
Epoch 37/100
33/33 [==============================] - 0s 2ms/step - loss: 41.7839
Epoch 38/100
33/33 [==============================] - 0s 2ms/step - loss: 40.7757
Epoch 39/100
33/33 [==============================] - 0s 2ms/step - loss: 42.7101
Epoch 40/100
33/33 [==============================] - 0s 2ms/step - loss: 42.4156
Epoch 41/100
33/33 [==============================] - 0s 2ms/step - loss: 43.5096
Epoch 42/100
33/33 [==============================] - 0s 2ms/step - loss: 39.6165
Epoch 43/100
33/33 [==============================] - 0s 2ms/step - loss: 42.7639
Epoch 44/100
33/33 [==============================] - 0s 2ms/step - loss: 41.4106
Epoch 45/100
33/33 [==============================] - 0s 2ms/step - loss: 39.4231
Epoch 46/100
33/33 [==============================] - 0s 2ms/step - loss: 39.8963
Epoch 47/100
33/33 [==============================] - 0s 2ms/step - loss: 38.0727
Epoch 48/100
33/33 [==============================] - 0s 2ms/step - loss: 39.5392
Epoch 49/100
33/33 [==============================] - 0s 2ms/step - loss: 38.7830
Epoch 50/100
33/33 [==============================] - 0s 2ms/step - loss: 40.8626
Epoch 51/100
33/33 [==============================] - 0s 2ms/step - loss: 40.6917
Epoch 52/100
33/33 [==============================] - 0s 2ms/step - loss: 38.2327
Epoch 53/100
33/33 [==============================] - 0s 2ms/step - loss: 41.5513
Epoch 54/100
33/33 [==============================] - 0s 2ms/step - loss: 40.3754
Epoch 55/100
33/33 [==============================] - 0s 2ms/step - loss: 38.6655
Epoch 56/100
33/33 [==============================] - 0s 2ms/step - loss: 37.6694
Epoch 57/100
33/33 [==============================] - 0s 2ms/step - loss: 38.7521
Epoch 58/100
33/33 [==============================] - 0s 2ms/step - loss: 40.0538
Epoch 59/100
33/33 [==============================] - 0s 2ms/step - loss: 34.8224
Epoch 60/100
33/33 [==============================] - 0s 2ms/step - loss: 37.8458
Epoch 61/100
33/33 [==============================] - 0s 1ms/step - loss: 37.0912
Epoch 62/100
33/33 [==============================] - 0s 2ms/step - loss: 37.4559
Epoch 63/100
33/33 [==============================] - 0s 2ms/step - loss: 38.8136
Epoch 64/100
33/33 [==============================] - 0s 2ms/step - loss: 38.3100
Epoch 65/100
33/33 [==============================] - 0s 2ms/step - loss: 37.5347
Epoch 66/100
33/33 [==============================] - 0s 2ms/step - loss: 38.9759
Epoch 67/100
33/33 [==============================] - 0s 2ms/step - loss: 41.7622
Epoch 68/100
33/33 [==============================] - 0s 1ms/step - loss: 34.9926
Epoch 69/100
33/33 [==============================] - 0s 2ms/step - loss: 36.9038
Epoch 70/100
33/33 [==============================] - 0s 2ms/step - loss: 36.4901
Epoch 71/100
33/33 [==============================] - 0s 1ms/step - loss: 36.2750
Epoch 72/100
33/33 [==============================] - 0s 1ms/step - loss: 36.1131
Epoch 73/100
33/33 [==============================] - 0s 1ms/step - loss: 34.5912
Epoch 74/100
33/33 [==============================] - 0s 2ms/step - loss: 35.2505
Epoch 75/100
33/33 [==============================] - 0s 2ms/step - loss: 35.0096
Epoch 76/100
33/33 [==============================] - 0s 2ms/step - loss: 35.1864
Epoch 77/100
33/33 [==============================] - 0s 2ms/step - loss: 33.9873
Epoch 78/100
33/33 [==============================] - 0s 2ms/step - loss: 38.7158
Epoch 79/100
33/33 [==============================] - 0s 2ms/step - loss: 33.1653
Epoch 80/100
33/33 [==============================] - 0s 2ms/step - loss: 36.0766
Epoch 81/100
33/33 [==============================] - 0s 2ms/step - loss: 33.0913
Epoch 82/100
33/33 [==============================] - 0s 2ms/step - loss: 34.5402
Epoch 83/100
33/33 [==============================] - 0s 2ms/step - loss: 31.8200
Epoch 84/100
33/33 [==============================] - 0s 2ms/step - loss: 32.4562
Epoch 85/100
33/33 [==============================] - 0s 2ms/step - loss: 33.5874
Epoch 86/100
33/33 [==============================] - 0s 2ms/step - loss: 35.2325
Epoch 87/100
33/33 [==============================] - 0s 2ms/step - loss: 33.4019
Epoch 88/100
33/33 [==============================] - 0s 2ms/step - loss: 31.4216
Epoch 89/100
33/33 [==============================] - 0s 2ms/step - loss: 30.0728
Epoch 90/100
33/33 [==============================] - 0s 2ms/step - loss: 32.4925
Epoch 91/100
33/33 [==============================] - 0s 2ms/step - loss: 31.2377
Epoch 92/100
33/33 [==============================] - 0s 2ms/step - loss: 30.9572
Epoch 93/100
33/33 [==============================] - 0s 2ms/step - loss: 30.8905
Epoch 94/100
33/33 [==============================] - 0s 2ms/step - loss: 27.9315
Epoch 95/100
33/33 [==============================] - 0s 2ms/step - loss: 28.9555
Epoch 96/100
33/33 [==============================] - 0s 2ms/step - loss: 30.2785
Epoch 97/100
33/33 [==============================] - 0s 1ms/step - loss: 28.1977
Epoch 98/100
33/33 [==============================] - 0s 1ms/step - loss: 28.4183
Epoch 99/100
33/33 [==============================] - 0s 2ms/step - loss: 29.9399
Epoch 100/100
33/33 [==============================] - 0s 1ms/step - loss: 26.4382

In [28]:
model.evaluate(X_test,y_test)

3/3 [==============================] - 0s 4ms/step - loss: 26.6034

26.603422164916992